DROP TABLE User_cart;
DROP TABLE Order_info_detail;
DROP TABLE Order_info_aggregate;
DROP TABLE User_browsing_history;

CREATE TABLE User_cart (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Order_info_aggregate (
    order_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount DECIMAL(12,2) NOT NULL,
    order_fulfillment_status INT NOT NULL DEFAULT 0
);


CREATE TABLE Order_info_detail (
    order_id INT NOT NULL,
    buyer_id INT NOT NULL,
    seller_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    product_fulfillment_status INT NOT NULL DEFAULT 0,
    FOREIGN KEY (order_id) REFERENCES Order_info_aggregate(order_id)
);


CREATE TABLE User_browsing_history (
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    view_times INT NOT NULL,
    last_view_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

