DROP TABLE Orders;
DROP TABLE Order_info_detail;

CREATE TABLE Orders (
    order_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    buyer_id INT NOT NULL,
    product_name TEXT NOT NULL,
    time_stamp DATE DEFAULT CURRENT_TIMESTAMP,
    total_amount INT NOT NULL,
    fulfillment_status TEXT NOT NULL
);

CREATE TABLE Order_info_detail (
    order_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    time_stamp DATE DEFAULT CURRENT_TIMESTAMP,
    buyer_id INT NOT NULL,
    seller_id INT NOT NULL,
    product_id INT NOT NULL,
    product_name TEXT NOT NULL,
    quantity INT NOT NULL,
    price float NOT NULL,
    total_amount INT NOT NULL,
    fulfillment_status TEXT NOT NULL
);

INSERT INTO Orders (order_id, buyer_id, product_name, time_stamp, total_amount, fulfillment_status)
VALUES (1, 1,  'table tennis', '2019-02-23 20:02:21.550', 516, 'YES');

INSERT INTO Orders (order_id, buyer_id, product_name, time_stamp, total_amount, fulfillment_status)
VALUES (2, 1, 'lamp',  '2020-02-23 20:02:21.550', 517, 'YES');

INSERT INTO Orders (order_id, buyer_id, product_name, time_stamp, total_amount, fulfillment_status)
VALUES (3,  1, 'ice cream', '2021-02-23 20:02:21.550', 518, 'YES');

INSERT INTO Orders (order_id, buyer_id, product_name, time_stamp, total_amount, fulfillment_status)
VALUES (4,  1, 'ice cream', '2022-02-23 20:02:21.550', 519, 'No');

INSERT INTO Orders (order_id, buyer_id, product_name, time_stamp, total_amount, fulfillment_status)
VALUES (5, 3,  'table tennis', '2019-02-23 20:02:21.550', 516, 'YES');

INSERT INTO Orders (order_id, buyer_id, product_name, time_stamp, total_amount, fulfillment_status)
VALUES (6, 3, 'lamp',  '2020-02-23 20:02:21.550', 517, 'YES');

INSERT INTO Orders (order_id, buyer_id, product_name, time_stamp, total_amount, fulfillment_status)
VALUES (7,  3, 'ice cream', '2021-02-23 20:02:21.550', 518, 'YES');

INSERT INTO Orders (order_id, buyer_id, product_name, time_stamp, total_amount, fulfillment_status)
VALUES (8,  3, 'ice cream', '2022-02-23 20:02:21.550', 519, 'No');



INSERT INTO Order_info_detail (order_id, time_stamp, buyer_id, seller_id, product_id, product_name, quantity, price, total_amount, fulfillment_status)
VALUES (1, '2022-02-23 20:02:21.550', 1, 1, 1, 'ice cream', 1, 20, 3, 'YES');

INSERT INTO Order_info_detail (order_id, time_stamp, buyer_id, seller_id, product_id, product_name, quantity, price, total_amount, fulfillment_status)
VALUES (2, '2022-02-23 20:02:21.550', 3, 1, 1, 'ice cream', 1, 20, 3, 'YES');

INSERT INTO Order_info_detail (order_id, time_stamp, buyer_id, seller_id, product_id, product_name, quantity, price, total_amount, fulfillment_status)
VALUES (3, '2023-02-23 20:02:21.550', 3, 2, 2, 'table', 1, 200, 3, 'YES');

INSERT INTO Order_info_detail (order_id, time_stamp, buyer_id, seller_id, product_id, product_name, quantity, price, total_amount, fulfillment_status)
VALUES (4, '2023-02-23 20:02:21.550', 3, 3, 4, 'mug', 1, 50, 4, 'NO');