DROP TABLE Balance;

CREATE TABLE Balance (
    trans_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    trans_date DATE DEFAULT CURRENT_TIMESTAMP,
    user_id INT NOT NULL,
    trans FLOAT DEFAULT 0 NOT NULL,
    trans_description TEXT  NOT NULL,
    balance FLOAT DEFAULT 0
    
);

INSERT INTO Balance (trans_id, trans_date, user_id, trans, trans_description, balance)
VALUES (1, '2019-02-23 20:02:21.550', 1, 0, 'Deposit from bank account', 0);

INSERT INTO Balance (trans_id, trans_date, user_id, trans, trans_description, balance)
VALUES (2, '2020-02-23 20:02:21.550', 1, 20, 'Deposit from bank account', 20);

INSERT INTO Balance (trans_id, trans_date, user_id, trans, trans_description, balance)
VALUES (3, '2020-02-23 20:02:21.550', 2, 50, 'Deposit from bank account', 50);

INSERT INTO Balance (trans_id, trans_date, user_id, trans, trans_description, balance)
VALUES (4, '2020-02-23 20:02:21.550', 3, 50, 'Deposit from bank account', 50);