DROP TABLE User_browsing_history;
DROP TABLE Orders;
DROP TABLE Orders_summary;
DROP TABLE User_cart;
DROP TABLE TABLE Product_type;
DROP TABLE Products;
DROP TABLE Users;
DROP TABLE Balance;
DROP TABLE Current_balance;
DROP TABLE Upvotes;
DROP TABLE Product_review;
DROP TABLE Seller_upvotes;
DROP TABLE Seller_review;


CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);


CREATE TABLE Product_type (
    type_id INT NOT NULL,
    ptype VARCHAR(255) NOT NULL
);

CREATE TABLE Products (
    product_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    seller_id INT NOT NULL REFERENCES Users(id),
    name VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    units_avail INT NOT NULL,
    available BOOLEAN DEFAULT TRUE,
    short_desc VARCHAR(255) NOT NULL DEFAULT 'I am a short description of the product',
    long_desc VARCHAR(65535) NOT NULL DEFAULT 'I am a really really long description of the product',
    type_id INT NOT NULL
);


CREATE TABLE User_cart (
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Orders_summary (
    order_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    buyer_id INT NOT NULL,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount DECIMAL(12,2) NOT NULL,
    order_status INT NOT NULL DEFAULT 0
);


CREATE TABLE Orders (
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    seller_id INT NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    fulfillment_status INT NOT NULL DEFAULT 0,
    FOREIGN KEY (order_id) REFERENCES Orders_summary(order_id)
);


CREATE TABLE User_browsing_history (
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    view_times INT NOT NULL,
    last_view_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Balance (
    trans_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    trans_date DATE DEFAULT CURRENT_TIMESTAMP,
    trans_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id INT NOT NULL,
    trans FLOAT DEFAULT 0 NOT NULL,
    trans_description TEXT  NOT NULL,
    balance FLOAT DEFAULT 0
    
);


CREATE TABLE Current_balance (
    user_id INT NOT NULL,
    current_balance FLOAT NOT NULL DEFAULT 0
);


CREATE TABLE Upvotes (
    user_id INT NOT NULL,
    review_id INT NOT NULL,
    UNIQUE(user_id, review_id)
);


CREATE TABLE Product_review (
    review_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    review_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    buyer_id INT NOT NULL,
    product_id INT NOT NULL,
    review_content TEXT NOT NULL,
    upvote INT NOT NULL,
    rating DECIMAL(3,2) NOT NULL,
    -- CHECK (rating <= 5.0 AND rating >= 0.0),
    UNIQUE(buyer_id, product_id)
);


CREATE TABLE Seller_upvotes (
    user_id INT NOT NULL,
    review_id INT NOT NULL,
    UNIQUE(user_id, review_id)
);


CREATE TABLE Seller_review (
    review_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    review_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    buyer_id INT NOT NULL,
    seller_id INT NOT NULL,
    review_content TEXT NOT NULL,
    upvote INT NOT NULL,
    rating DECIMAL(3,2) NOT NULL, 
    -- CHECK (rating <= 5.0 AND rating >= 0.0),
    UNIQUE(buyer_id, seller_id)
);




